const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "./images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Addidas Fit Shirt",
      category: "Shirts",
      image: "./images/p2.jpg",
      price: 100,
      brand: "Addidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "./images/p3.jpg",
      price: 220,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 18,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "./images/p4.jpg",
      price: 89,
      brand: "Nike",
      rating: 4.0,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pant",
      category: "Pants",
      image: "./images/p5.jpg",
      price: 55,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Addidas fit pant",
      category: "Pants",
      image: "./images/p6.jpg",
      price: 144,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 16,
      description: "high quality product",
    },
  ],
};

export default data;
